version: "3.7"

services:
  frontend:
    build:
      dockerfile: frontend.Dockerfile
    container_name: frontend
    restart: always

  backend:
    build:
      dockerfile: backend.Dockerfile
    container_name: backend
    restart: always

  nginx:
    image: nginx:1.19
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./assets:/usr/local/nginx/html
    depends_on:
      - frontend
      - backend
