version: "3.7"

services:
  frontend:
    build:
      dockerfile: frontend.Dockerfile
    container_name: frontend
    restart: always

  backend:
    build:
      dockerfile: backend.Dockerfile
    container_name: backend
    restart: always
