version: "3.7"

services:
  frontend:
    build:
      dockerfile: Dockerfile.frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"

  backend:
    build:
      dockerfile: Dockerfile.backend
    container_name: backend
    restart: always
    ports:
      - "3001:8086"

  nginx:
    image: nginx:1.19
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    links:
      - frontend
      - backend
