version: "3.7"

services:
  frontend:
    ports:
      - 80:80
    build:
      dockerfile: ./docker/frontend.Dockerfile
    container_name: frontend
    restart: always

  backend:
    build:
      dockerfile: ./docker/backend.Dockerfile
    container_name: backend
    restart: always
