/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionCard: typeof import('./components/ActionCard.vue')['default']
    ActionInfo: typeof import('./components/ActionInfo.vue')['default']
    CharacterCard: typeof import('./components/CharacterCard.vue')['default']
    CharacterInfo: typeof import('./components/CharacterInfo.vue')['default']
    CostIcon: typeof import('./components/CostIcon.vue')['default']
    DicesNumber: typeof import('./components/DicesNumber.vue')['default']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElementIcon: typeof import('./components/ElementIcon.vue')['default']
    ElTag: typeof import('element-plus/es')['ElTag']
    EnergyIcon: typeof import('./components/EnergyIcon.vue')['default']
    GameContainer: typeof import('./components/GameContainer.vue')['default']
    PlayerID: typeof import('./components/PlayerID.vue')['default']
    PreviewCard: typeof import('./components/PreviewCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectedIcon: typeof import('./components/SelectedIcon.vue')['default']
    Skill: typeof import('./components/Skill.vue')['default']
    SkillButton: typeof import('./components/SkillButton.vue')['default']
    SkillInfo: typeof import('./components/SkillInfo.vue')['default']
    SummonCard: typeof import('./components/SummonCard.vue')['default']
    SummonInfo: typeof import('./components/SummonInfo.vue')['default']
    SupportCard: typeof import('./components/SupportCard.vue')['default']
    SupportInfo: typeof import('./components/SupportInfo.vue')['default']
    SwitchRoundButton: typeof import('./components/SwitchRoundButton.vue')['default']
  }
}
