name: Build Vite

on:
  push:
    branches: ["master", "vite-vue3"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: pnpm install
      - name: Static HTML export with Nuxt
        run: pnpm build
